services:
  ndtp-emu:
    image: ndtp-telemetry-emulator:1.0
    container_name: ndtp-emu
    ports:
      - "18080:18080"

  db:
    image: postgres:16-alpine
    container_name: mthack-db
    environment:
      POSTGRES_USER: mthack
      POSTGRES_PASSWORD: mthack
      POSTGRES_DB: mthack
    ports:
      - "5433:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"

  ml-model:
    build: ./ml-model
    container_name: mthack-ml
    environment:
      DB_DSN: postgresql://mthack:mthack@db:5432/mthack
      MODEL_PATH: /app/model.txt
      POINTS_CSV: /app/data/points.csv
      SCHEDULE_CSV: /app/data/schedule_plan.csv
      INTERVAL: 20
    volumes:
      - "./dataset/validate/points.csv:/app/data/points.csv:ro"
      - "./dataset/validate/schedule_plan.csv:/app/data/schedule_plan.csv:ro"
      - "./dataset/validate/traffic.csv:/app/data/traffic.csv:ro"

  backend:
    build: ./backend
    container_name: mthack-backend
    ports:
      - "8000:8000"
    environment:
      NDTP_EMULATOR_URL: http://ndtp-emu:18080
      NDTP_CSV_INTERVAL: 5
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: mthack
      DB_PASSWORD: mthack
      DB_NAME: mthack
    volumes:
      - "./data:/app/data"
    depends_on:
      - ndtp-emu
      - db
      - ml-model

  grafana:
    image: grafana/grafana:13.2.2
    container_name: mthack-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_VIEWER_CAN_EDIT: "true"
      GF_PANELS_DISABLE_SANITIZE_HTML: "true"
    volumes:
      - "./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro"
      - "./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro"
      - "./grafana/provisioning/alerting:/etc/grafana/provisioning/alerting:ro"
      - "./grafana/dashboards:/var/lib/grafana/dashboards:ro"
      - "grafana-data:/var/lib/grafana"
    depends_on:
      - db

volumes:
  grafana-data: